apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: match-name
spec:
  version: "v0.1.3"
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/gerald1248/kubectl-match-name/releases/download/v0.1.3/kubectl-match_name-darwin-amd64.zip
    sha256: 69c72e56d96688f6d32d21d1ca111573c6568ef9f4529e8616f97e1f4d97c0d6
    files:
    - from: "*"
      to: "."
    bin: kubectl-match_name
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/gerald1248/kubectl-match-name/releases/download/v0.1.3/kubectl-match_name-linux-amd64.zip
    sha256: ad1cddc5eb0f97ff7c872228fa871a09967ed00a0d10c8c36a05463dff70f413
    files:
    - from: "*"
      to: "."
    bin: kubectl-match_name
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/gerald1248/kubectl-match-name/releases/download/v0.1.3/kubectl-match_name-windows-amd64.zip
    sha256: aa787ebf95abdd9cebba2010b52beea3d5b9b976ff31b5f9102e1f711aff39e8
    files:
    - from: "*"
      to: "."
    bin: kubectl-match_name.exe
  shortDescription: Match names of pods and other API objects
  caveats: |
    API object coverage is incomplete.
  description: |
    This plugin allows fast regex matching for the names of pods and other API objects. It reduces typing and simplifies automation.
